# This is going to be my basic workflow
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install terraform
              uses: hashicorp/setup-terraform@v1
            
            - name: Init terraform
              run: terraform init

            - name: Plan terraform
              run: terraform plan

            - name: Apply terraform
              run: terraform apply -auto-approve
              env:
                TF_VAR_ssh_public_key: ${{ secrets.AWS_SSH_PUBLIC_KEY }}

            - name: Setup docker buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            
            - name: Build and push Docker image
              run: |
                docker build -t ${{ secrets.DOCKER_USERNAME }}/demo:latest .
                docker push ${{ secrets.DOCKER_USERNAME }}/demo:latest

            - name: SSH into EC2 and run Docker container
              uses: appleboy/ssh-action@v0.1.4
              with:
                host: ${{ steps.terraform.outputs.instance_ip }}
                username: ec2-user
                key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
                script: |
                  docker pull ${{ secrets.DOCKER_USERNAME }}/hello-world:latest
                  docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/hello-world:latest

            - name: Test the application
              run: |
                curl http://$(terraform output -raw instance_ip)

            - name: Destroy Terraform
              run: terraform destroy -auto-approve